package src.storage;

import java.sql.Connection;
import java.sql.SQLException;

public class Migrations {

    private static Migrations migrationsInstance = null;

    private Migrations() {
    }

    public static Migrations getInstance() {
        if (migrationsInstance == null) migrationsInstance = new Migrations();
        return migrationsInstance;
    }

    public void createTables() {
        String createWarehouse = """
                create table WAREHOUSE
                (
                    NAME  VARCHAR2(30) not null unique,
                    VALUE NUMBER(8) default 0
                );
                """;
        String createOrder = """
                create table ORDERS
                (
                    LIEFERUNG  NUMBER(1),
                    PLZ        NUMBER(8),
                    FIRSTNAME  VARCHAR2(30),
                    SECONDNAME VARCHAR2(30),
                    ADDRESS    VARCHAR2(50),
                    FLOOR      NUMBER(3),
                    TELEFON    VARCHAR2(30),
                    SUM        NUMBER(30),
                    ORDERID    NUMBER generated by default on null as identity
                );
                """;

        String createTransactions = """
                create table transactions
                (
                    VALUE          NUMBER(30),
                    order_id       NUMBER,
                    transaction_id NUMBER generated by default on null as identity
                );
                """;

        Connection connection = null;

        try {
            connection = OracleDsSingleton.getInstance().getConnection();
            connection.prepareStatement(createWarehouse).executeUpdate();
            connection.prepareStatement(createOrder).executeUpdate();
            connection.prepareStatement(createTransactions).executeUpdate();
        } catch (SQLException ignored) {
            // TODO fix: ORA-00922: missing or invalid option
//            ignored.printStackTrace();
        } finally {
            try {
                if (connection != null) connection.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
}
